apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Backstage Codebase
  annotations:
    github.com/project-slug: jamesAtIntegratnIO/backstage-demo
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-namespace: backstage
    backstage.io/kubernetes-label-selector: app=backstage
    argocd/app-name: backstage
spec:
  type: service
  owner: user:default/jamesatintegratnio
  lifecycle: homeprod
  system: backstage
  dependsOn:
    - resource/backstage-db
    - resource/backstage-manifests
